import AppKit
import BouncerCore

/// Opt-in passive observation. A listen-only tap cannot remove, modify or replay
/// events. Its callback reads modifier identity/timing, never typed characters.
@MainActor
final class ModifierDoubleTap {
    private var tap: CFMachPort?
    private var source: CFRunLoopSource?
    private var detector = ModifierDoubleTapDetector()
    private var trigger: CorrectionTrigger = .keyCombination
    private var revision: UInt64 = 0
    private var activationObserver: NSObjectProtocol?
    private let action: () -> Void
    var unavailable: (() -> Void)?
    var isRunning: Bool { tap.map { CGEvent.tapIsEnabled(tap: $0) } ?? false }

    init(action: @escaping () -> Void) { self.action = action }

    // System-defined media events use the same type value as NSEvent.
    private static let systemDefined = CGEventType(rawValue: UInt32(NSEvent.EventType.systemDefined.rawValue))!
    private static let mask: CGEventMask = [CGEventType.flagsChanged, .keyDown, .keyUp,
        .leftMouseDown, .rightMouseDown, .otherMouseDown, .scrollWheel,
        .leftMouseDragged, .rightMouseDragged, .otherMouseDragged, systemDefined]
        .reduce(0) { $0 | (CGEventMask(1) << $1.rawValue) }

    @discardableResult
    func start(_ trigger: CorrectionTrigger) -> Bool {
        if self.trigger == trigger, isRunning { return true }
        stop()
        guard trigger != .keyCombination, CGPreflightListenEventAccess() else { return false }
        self.trigger = trigger
        guard let tap = CGEvent.tapCreate(tap: .cgSessionEventTap, place: .tailAppendEventTap,
            options: .listenOnly, eventsOfInterest: Self.mask, callback: { _, type, event, context in
                if let context {
                    MainActor.assumeIsolated {
                        Unmanaged<ModifierDoubleTap>.fromOpaque(context).takeUnretainedValue().receive(type, event: event)
                    }
                }
                return Unmanaged.passUnretained(event)
            }, userInfo: Unmanaged.passUnretained(self).toOpaque()) else { return false }
        guard let source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, tap, 0) else {
            CFMachPortInvalidate(tap); return false
        }
        self.tap = tap; self.source = source
        CFRunLoopAddSource(CFRunLoopGetMain(), source, .commonModes)
        CGEvent.tapEnable(tap: tap, enable: true)
        activationObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification, object: nil, queue: .main) { [weak self] _ in
                MainActor.assumeIsolated { self?.interrupt() }
            }
        return isRunning
    }

    private func interrupt() { detector.reset(); revision &+= 1 }

    private func receive(_ type: CGEventType, event: CGEvent) {
        if type == .tapDisabledByTimeout || type == .tapDisabledByUserInput {
            interrupt()
            if type == .tapDisabledByTimeout, CGPreflightListenEventAccess(), let tap {
                CGEvent.tapEnable(tap: tap, enable: true)
            } else { stop(); unavailable?() }
            return
        }
        if type == Self.systemDefined, NSEvent(cgEvent: event)?.subtype.rawValue != 8 { return }
        revision &+= 1
        // Only modifier changes need a foreground context. Typing and pointer
        // events simply reset the detector, without decoding their contents.
        let pid = type == .flagsChanged ? (NSWorkspace.shared.frontmostApplication?.processIdentifier ?? 0) : 0
        guard Self.observe(type, event: event, trigger: trigger, context: pid, detector: &detector) else { return }
        let expected = revision
        // Do not start capture/model work inside the event callback. A queued input
        // or app switch invalidates this delivery before it can capture a newer draft.
        Task { [weak self] in
            guard let self, revision == expected, isRunning,
                  NSWorkspace.shared.frontmostApplication?.processIdentifier == pid else { return }
            action()
        }
    }

    static func observe(_ type: CGEventType, event: CGEvent, trigger: CorrectionTrigger,
                        context: pid_t, detector: inout ModifierDoubleTapDetector) -> Bool {
        if type == systemDefined {
            // Media-key events (subtype 8) interrupt Fn combinations. Other system
            // events can be generated by the Globe key itself and are left alone.
            if NSEvent(cgEvent: event)?.subtype.rawValue == 8 { detector.reset() }
            return false
        }
        guard type == .flagsChanged else { detector.reset(); return false }
        let key = event.getIntegerValueField(.keyboardEventKeycode)
        guard key >= 0, key <= UInt16.max else { detector.reset(); return false }
        return detector.update(trigger: trigger, keyCode: UInt16(key), flags: event.flags.rawValue,
                               timestamp: Double(event.timestamp) / 1_000_000_000, context: context)
    }

    func stop() {
        interrupt()
        if let activationObserver { NSWorkspace.shared.notificationCenter.removeObserver(activationObserver) }
        activationObserver = nil
        if let tap { CGEvent.tapEnable(tap: tap, enable: false); CFMachPortInvalidate(tap) }
        if let source { CFRunLoopRemoveSource(CFRunLoopGetMain(), source, .commonModes) }
        tap = nil; source = nil; trigger = .keyCombination
    }

    isolated deinit {
        if let activationObserver { NSWorkspace.shared.notificationCenter.removeObserver(activationObserver) }
        if let tap { CGEvent.tapEnable(tap: tap, enable: false); CFMachPortInvalidate(tap) }
        if let source { CFRunLoopRemoveSource(CFRunLoopGetMain(), source, .commonModes) }
    }
}
